server:
  port: 9090
  servlet:
    context-path: /IESWebApp
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: pavan@123
    url: jdbc:oracle:thin:@localhost:1521/SYSTEM
    username: system
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

        smtp:
          starttls:
            enable: true
          auth: true
